### ISSUE TITLE
Android app crashes when trying to scan document.

### ISSUE THREAD

**Issue by ghost** [abbyysdk/RTR-SDK.Cordova#10]
Installed the Abbyy plugin version 1.0.12, iOS works fine when integrated with our project but on Android the app crashes when trying to scan the document. I was able to debug and see the log for  Null Point Exception in Android studio console( Attached is the screenshot of the error).
![andDataCaptureErr](https://user-images.githubusercontent.com/32644223/66678444-e7566280-ec39-11e9-85c6-9380336034f5.jpg)

Followed the src code config.xml file, have set preference of minSdk to 21 for android platform and installed the cordova-android version 8.0.0

Tried to reach Abbyy Support many times  regarding this issue, but no response for the product that's already paid for.

**Comment by andreichenchik** [comment]
Hello @sudhachimata 
This should be definitely fixed for now.
Please use updated version of plugin if you still having this issue.
