### ISSUE TITLE
AbbyyRtrSdk is undefined 

### ISSUE THREAD

**Issue by RacknerFrank** [abbyysdk/RTR-SDK.Cordova#11]
I was able to get the sample app running but when I was able to get the plugin added to my own app (which was pretty difficult and required me to change my app id to `com.abbyy.rtrcordovasample`) I get `ReferenceError: AbbyyRtrSdk is not defined`. How is it supposed to be imported? I don't see how it's happening in the sample app.

Any ideas?

**Comment by p3v9d5ui** [comment]
@RacknerFrank -- I just submitted issue #12 which is related to this. Of course, it can't be expected to change your own app's ID to com.abbyy.rtrcordovasample. I had to edit every instance of this in the plugin's code to use my own app ID instead.

**Comment by andreichenchik** [comment]
Thank you for posting this issue
This is fixed in latest releases

If you will have any questions - please let me know, I will be happy to help

Same as for #12
