### ISSUE TITLE
Do we have to change com.abbyy.rtrcordovasample in code?

### ISSUE THREAD

**Issue by p3v9d5ui** [abbyysdk/RTR-SDK.Cordova#12]
The instructions for using this plugin seem to be missing an important step:

The code tries to import this package: com.abbyy.rtrcordovasample. But this is a class that is auto-generated by Gradle, but is never generated because the name comes from the app's bundle ID. Only the Abby sample application uses the ID "com.abbyy.rtrcordovasample". To get this plugin to work, you have to replace all instances of this with your own app's ID.

Surely there is a better way to do this, intsead of requiring users to edit the plugin code? Or am I missing something?

**Comment by al0b** [comment]
Thank you, we will fix this issue in the upcoming release of the plugin. Currently replacing the package name is the way to workaround the bug.

**Comment by p3v9d5ui** [comment]
Thanks. Do you have any information on what will be included in the next release, and also a release date?

**Comment by andreichenchik** [comment]
Thank you for posting this issue, sorry for the delay, this is fixed in the latest release and release prior to that.
