### ISSUE TITLE
www folder overwritten during build

### ISSUE THREAD

**Issue by bchrisb** [abbyysdk/RTR-SDK.Cordova#14]
In the Getting started section, one of the first instructions is:

- Create the www/rtr_assets subdirectory in the project

I create this folder and follow the other set up steps but when I run `ionic cordova build android`, the `www` folder is deleted and recreated, overwriting the `rtr_assets` folder I create earlier?

**Comment by ernestasanov** [comment]
Hello,
You probably put the www/rtr_assets in the Android platform-specific folder (platforms\android\app)?
Once you've created a Cordova project, there is a www/ folder in the project root. That's where you should put the rtr_assets folder.

**Comment by bitvalser** [comment]
> In the Getting started section, one of the first instructions is:
> 
> * Create the www/rtr_assets subdirectory in the project
> 
> I create this folder and follow the other set up steps but when I run `ionic cordova build android`, the `www` folder is deleted and recreated, overwriting the `rtr_assets` folder I create earlier?

You can configure the resources in the angular.json folder:
1) Move your rtr_assets folder to src
2) open angular.json and find the "assets" property (projects.app.architect.build.options)
3) add new data to the array
`{
"glob": "** / *",
"input": "src / rtr_assets",
"output": "rtr_assets"
} `

You can customize the paths as you like
Now run the `ionic cordova build android`, rtr_assets will be copied to the www folder
Tested with ionic 4 and angular 8 (I think you can find this option also in lower versions of angular and ionic)

**Comment by al0b** [comment]
We added Ionic sample with instructions how to configure your Ionic project, please check https://github.com/abbyy/RTR-SDK.Cordova/tree/master/sample-ionic
