### ISSUE TITLE
I can't get libraries SDK

### ISSUE THREAD

**Issue by agarate** [abbyysdk/RTR-SDK.Cordova#18]
How can I get the necessary libraries? I have registered on Abby's page and they tell me that Cloud SDK, but I need the libraries to test this plugin.

**Comment by al0b** [comment]
This plugin requires the ABBYY Mobile Capture assets, which differ for Android and iOS, and a license file. You can request ABBYY Mobile Capture trial version on the [ABBYY website](http://www.abbyy.com/en-eu/real-time-recognition-sdk/#request-demo).
