### ISSUE TITLE
error on sample : Could not load some required resource files. Make sure to configure 'assets' to your application and specify correct licence file name

### ISSUE THREAD

**Issue by GorianDriza** [abbyysdk/RTR-SDK.Cordova#2]

**Comment by mohammedmatar** [comment]
i have the same problem, i am using ionic3, is there any solution or hint, i copied the license everywhere in app but with no luck.

**Comment by Anujmoglix** [comment]
Same issue for me . Not able to run this . I am getting error "Could not load some required resource files. Make sure to configure 'assets' directory in your application and specify correct 'license file name'. See logcat for details."  . Why i am getting this , i have did everything same as mentioned in the doc , Waiting for reply from owner .

**Comment by bitvalser** [comment]
I also use ionic [dependency](https://ionicframework.com/docs/native/abbyy-rtr/)
My steps:
1) in the src/assets folder, create the License folder (src/assets/License) and copy the license file (<license_name>.License)
2) just in case, copy the license file to src/assets
3) configure angular.json to copy rtr_assets to www folder
4) call the startDataCapture method
`this.abbyyRTR
.startDataCapture ({
licenseFileName: '<license_name>.License',
profile: '<pattern_name>'
}) `

Work good for me

**Comment by al0b** [comment]
`assets` and license are vital files for working of the Mobile Capture SDK, so in your built .apk or .ipa these files should be.
Example of iOS app bundle:
```
	App.app/
		...
		dictionaries/
			...
		patterns/
			...
		...
		Frameworks/
			AbbyyRtrSDK.framework
			...
		App
		MobileCapture.License
		...
```

Please check [Cordova](https://help.abbyy.com/en-us/mobilecapturesdk/1/cordova_help/cordova-getting-started) and [Ionic](https://help.abbyy.com/en-us/mobilecapturesdk/1/ionic_help/ionic-getting-started) instructions or examine our developer samples ([sample-cordova](https://github.com/abbyy/RTR-SDK.Cordova/tree/master/sample-cordova) and [sample-ionic](https://github.com/abbyy/RTR-SDK.Cordova/tree/master/sample-ionic)).
