### ISSUE TITLE
Making it work with Ionic framework

### ISSUE THREAD

**Issue by ghost** [abbyysdk/RTR-SDK.Cordova#5]
I have tried to follow the instructions given by the AbbyyRTR plugin readme file, but cant make it work when i run "ionic serve". Have added the lib folder referenced them from the build.gradle and .xxconfig files, but when i run the app in the Ionic developer app and try to start the abbyRTR.startcapturetext() then i get and error message telling me "plugin_not_installed". I don't get it. Can anybody help me, would be really happy to get hints or instructions on how to make it work. Even an explanation to why it might not be possible to test via "ionic serve"

**Comment by DeanWilliamMills** [comment]
I am also trying to figure it out with Ionic 3. Followed the ReadMe to the point and had to make some changes for cordova-android 7.1.1, but getting this error when calling **startTextCapture()**: 
"**Unspecified error while loading the engine. See logcat for details.**"

Any help would be much appreciated.

@MadsFox just remember when you do "serve", the native plugins are not available. You need to do a "run" on an emulator or actual device.

**Comment by ghost** [comment]
@DeanWilliamMills i made the barcodescanner Work through serve, is the difference its NOT “native” to Ionic?

**Comment by kzrfaisal** [comment]
Hi @MadsFox , @DeanWilliamMills ,
Can anyone of you provide steps for making it work with ionic. I can't find any ionic documentation for this plugin.

**Comment by marcfeliu** [comment]
Same problem here

**Comment by jay-b** [comment]
Also need some help here, can't find any example code or docs. to help integrate with Ionic.

**Comment by anaji** [comment]
Hi,
this link could be useful:

- https://ionicframework.com/docs/native/abbyy-rtr/

**Comment by pareshgami** [comment]
Created one tutorial for rtr text reading. Hope that's helpful.

https://www.youtube.com/watch?v=vIzZe8irmRs

**Comment by al0b** [comment]
We added Ionic sample with instructions how to add the plugin to your Ionic app https://github.com/abbyy/RTR-SDK.Cordova/tree/master/sample-ionic.
