### ISSUE TITLE
Not working with Android 6.4.0

### ISSUE THREAD

**Issue by RZR666** [abbyysdk/RTR-SDK.Cordova#7]
```
Ionic 4 RC0
Android 6.4.0
@ionic-native/abbyy-rtr": "^5.0.0-beta.22"
```

Ok, I've placed this asset folder everywhere in the Ionic project and no joy.

**Logcat Error**

java.io.FileNotFoundException: AbbyyRtrSdk.license

**And the places I've put the resources...**
 
ionic_project/www/rtr_assets/patterns
ionic_project/www/rtr_assets/dictionaries
ionic_project/www/rtr_assets/AbbyyRtrSdk.license

ionic_project/platforms/android/assets/www/rtr_assets/patterns
ionic_project/platforms/android/assets/www/rtr_assets/dictionaries
ionic_project/platforms/android/assetswww/rtr_assets/AbbyyRtrSdk.license

ionic_project/platforms/android/www/rtr_assets/patterns
ionic_project/platforms/android/www/rtr_assets/dictionaries
ionic_project/platforms/android/www/rtr_assets/AbbyyRtrSdk.license

ionic_project/platforms/android/platform_www/rtr_assets/patterns
ionic_project/platforms/android/platform_www/rtr_assets/dictionaries
ionic_project/platforms/android/platform_www/rtr_assets/AbbyyRtrSdk.license

Has anyone managed to get this working?

Thanks

**Comment by andreichenchik** [comment]
Hello @RZR666 seems like a misconfiguration of the assets in the project. As for now we don't have official support for ionic, but we will have it soon. Please let me know if you still having this issue
