### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by fhackenb** [abbyysdk/RTR-SDK.Cordova#8]
I tried out the sample app and it crashes on iOS during document detection. The camera opens and the edge / document detection seems to work as it moves around with the camera to capture the document & then the app just crashes when it looks like it's found the optimal capture.

Here's the last few lines from xcode:

```
RTRCordovaSample[282:9062] Received Event: deviceready
2019-10-09 13:22:28.074423-0400 RTRCordovaSample[282:9062] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-10-09 13:22:28.076227-0400 RTRCordovaSample[282:9062] [MC] Reading from public effective user settings.
Vital data file DIQClassifier.imodel was not found.

Internal Program Error:

Assertion failed: ()

/Build/OCRT-master_16_1_725_0/FineObjects/inc/Object.h, 480

Function: 

(lldb) 
```

**Comment by fhackenb** [comment]
(I ran it on an iPad if that makes a difference)

**Comment by YetAnotherRzmn** [comment]
Hello!
Most likely you forgot to add assets to sample project. The instructions have paragraph 2.2:

> Copy Mobile Capture SDK assets (patterns and dictionaries) and license file (AbbyyRtrSdk.license) to www/rtr_assets.

DIQClassifier.imodel is located in the assets/patterns folder, It must be copied to the application via `after_plugin_add` hook.

**Comment by andreichenchik** [comment]
Hello @fhackenb!
Hope everything is okay with your application. I will close the issue for now since instructions from @YetAnotherRzmn should be enough. 

Please let me know if you will have any questions.
